### List Locations
GET {{SERVERURL}}:{{PORT}}/api/locations

### Get Location
GET {{SERVERURL}}:{{PORT}}/api/locations/5f7b3b3b7f3b3b3b3b3b3b3b

### Create Location
POST {{SERVERURL}}:{{PORT}}/api/locations
Content-Type: application/json

{
  "name": "W1",
  "lattitude": 123.456789,
  "longitude": 98.7654321
}

### Update Location
PATCH {{SERVERURL}}:{{PORT}}/api/locations/warehouses
Content-Type: application/json

{
  "chassis": "1234567890"
}

### Delete Location
DELETE {{SERVERURL}}:{{PORT}}/api/locations/5f7b3b3b7f3b3b3b3b3b3b3b

