### List Locations
GET {{SERVERURL}}:{{PORT}}/api/locations

### Get Location
GET {{SERVERURL}}:{{PORT}}/api/locations/c5d618ea-8dd7-43ce-a7fd-1b6c0d14e919

### Create Location
POST {{SERVERURL}}:{{PORT}}/api/locations
Content-Type: application/json

{
  "name": "WareHouse 12",
  "lattitude": 123.456789,
  "longitude": 98.7654321
}

### Update Location
PATCH {{SERVERURL}}:{{PORT}}/api/locations/dc52a13f-9eb2-46bb-97a2-a8779e7f4b8a
Content-Type: application/json

{
  "address": "Bell Haven Gardens"
}

### Delete Location
DELETE {{SERVERURL}}:{{PORT}}/api/locations/78d45082-d62f-46ff-9c0c-f11e24381ffd

