### List Trucks
GET {{SERVERURL}}:{{PORT}}/api/trucks
Authorization: Basic YWRtaW48

### Get Truck
GET {{SERVERURL}}:{{PORT}}/api/trucks/b2b46285-5f2e-4843-8237-44cc2054e2d5
Authorization: Basic YWRtaW48

### Create Truck
POST {{SERVERURL}}:{{PORT}}/api/trucks
Content-Type: application/json
Authorization: Basic YWRtaW48

{
  "name": "Truck 1",
  "model": "Model 1",
  "year": 2020,
  "licensePlate": "ABC-1234",
  "make": "Make 1",
  "brand": "Brand 1",
  "capacity": 1000,
  "locationUuid": "fb0af2c6-6af3-4d9b-9e75-5728d8cd55bd"
}

### Update Truck
PATCH {{SERVERURL}}:{{PORT}}/api/trucks/038f6b3e-aacd-41a7-8a3d-dc7477a28ce3
Content-Type: application/json
Authorization: Basic YWRtaW48

{
  "brand": "Brand 26",
  "locationUuid": "1df89b57-853d-4aee-933f-25cecacd3323"
}

### Delete Truck
DELETE {{SERVERURL}}:{{PORT}}/api/trucks/bac41b33-d076-4ade-ad08-8682123c40cd
Authorization: Basic YWRtaW48

