import { expect, test } from '@playwright/test'

import { randomUUID } from 'crypto'

const __APP_URL__ = 'http://localhost:6565'

test('load page', async ({ page }) => {
  await page.goto(__APP_URL__)

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Fulfilments TMS/)
})

test('to show login screen on load', async ({ page }) => {
  await page.goto(__APP_URL__)
  await page.getByTestId('login-link').first().click()
  await expect(page).toHaveURL(__APP_URL__)
})

test('test create location and truck', async ({ page }) => {
  const licensePlate = randomUUID().slice(5)
  await page.goto('http://localhost:6565/login')
  await page.getByRole('link', { name: 'Normal User Normal User has' }).click()
  await page.getByRole('link', { name: 'Locations' }).click()
  await page.getByRole('link', { name: '+' }).click()
  await page.locator('input[name="name"]').click()
  await page.locator('input[name="name"]').fill('Warehouse 1')
  await page.locator('input[name="name"]').press('Tab')
  await page.locator('input[name="address"]').fill('Address Field 1')
  await page.locator('input[name="address"]').press('Tab')
  await page.locator('input[name="lattitude"]').fill('52.3676')
  await page.locator('input[name="lattitude"]').press('Tab')
  await page.locator('input[name="longitude"]').fill('4.9041')
  await page.getByRole('button', { name: 'Submit' }).click()
  await page.getByRole('link', { name: '+' }).click()
  await page.locator('input[name="name"]').click()
  await page.locator('input[name="name"]').fill('Warehouse 2')
  await page.locator('input[name="name"]').press('Tab')
  await page.locator('input[name="address"]').fill('Address Field 2')
  await page.locator('input[name="address"]').press('Tab')
  await page.locator('input[name="lattitude"]').fill('52.4676')
  await page.locator('input[name="lattitude"]').press('Tab')
  await page.locator('input[name="longitude"]').fill('4.9141')
  await page.getByRole('button', { name: 'Submit' }).click()
  await expect(page.getByRole('cell', { name: 'Warehouse 1' }).first()).toBeVisible()
  await page.getByRole('link', { name: 'Trucks' }).click()
  await page.getByRole('link', { name: '+' }).click()
  await page.locator('input[name="name"]').click()
  await page.locator('input[name="name"]').fill('Test Truck 1')
  await page.locator('input[name="name"]').press('Tab')
  await page.locator('input[name="licensePlate"]').fill(licensePlate)
  await page.locator('input[name="licensePlate"]').press('Tab')
  await page.getByRole('combobox').press('Tab')
  await page.locator('input[name="make"]').fill('Make 1')
  await page.locator('input[name="make"]').press('Tab')
  await page.locator('input[name="brand"]').fill('Brand 1')
  await page.locator('input[name="brand"]').press('Tab')
  await page.locator('input[name="model"]').fill('Model 1')
  await page.locator('input[name="model"]').press('Tab')
  await page.locator('input[name="year"]').fill('2022')
  await page.locator('input[name="year"]').press('Tab')
  await page.locator('input[name="capacity"]').fill('2000')
  await page.locator('input[name="capacity"]').press('Tab')
  await page.getByRole('button', { name: 'Submit' }).click()
  await page.getByText('Truck created successfully').click()
  await expect(page.getByRole('cell', { name: licensePlate })).toBeVisible()
})

test('test create a truck', async ({ page }) => {
  await page.goto('http://localhost:6565/login')
  await page.getByRole('link', { name: 'Admin User Admin User (has' }).click()
  await page.getByRole('link', { name: 'Trucks' }).click()
  await page.getByRole('link', { name: '+' }).click()
  await page.locator('input[name="name"]').click()
  await page.locator('input[name="name"]').fill('Test Truck 2')
  await page.locator('input[name="licensePlate"]').click()
  await page.locator('input[name="licensePlate"]').fill('TRUCK2')
  await page.locator('input[name="make"]').click()
  await page.locator('input[name="make"]').fill('Make 1')
  await page.locator('input[name="brand"]').click()
  await page.locator('input[name="brand"]').fill('Brand 2')
  await page.locator('input[name="model"]').click()
  await page.locator('input[name="model"]').fill('Model 2')
  await page.locator('input[name="year"]').click()
  await page.locator('input[name="year"]').fill('2024')
  await page.locator('input[name="capacity"]').click()
  await page.locator('input[name="capacity"]').fill('2000')
  await page.getByRole('button', { name: 'Submit' }).click()
  await expect(page.getByRole('cell', { name: 'TRUCK2' })).toBeDefined()
})
